// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/","parentId":"@@/global-layout","id":"2"},"3":{"path":"/","parentId":"2","id":"3"},"4":{"path":"/users","parentId":"2","id":"4"},"5":{"path":"/shops","parentId":"2","id":"5"},"6":{"path":"/products","parentId":"2","id":"6"},"7":{"path":"/categories","parentId":"2","id":"7"},"8":{"path":"/orders","parentId":"2","id":"8"},"9":{"path":"/banners","parentId":"2","id":"9"},"10":{"path":"/configs","parentId":"2","id":"10"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Users__index" */'@/pages/Users/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Shops__index" */'@/pages/Shops/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Products__index" */'@/pages/Products/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Categories__index" */'@/pages/Categories/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Orders__index" */'@/pages/Orders/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Banners__index" */'@/pages/Banners/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Configs__index" */'@/pages/Configs/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/AI/codex/FreshSource/admin-web/src/layouts/index.tsx')),
},
  };
}
